services:
  - type: web
    name: telegram-summary-bot
    runtime: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install setuptools==65.0.0
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: FOLDER_ID
        sync: false
      - key: API_KEY
        sync: false
      - key: WHISPER_MODEL
        value: tiny